name: CI/CD Pipeline

# This workflow demonstrates key DevOps concepts:
# - Continuous Integration: Automated testing and building
# - Continuous Deployment: Automated deployment to GitHub Pages
# - Code Quality: Linting and formatting checks
# - Security: Dependency vulnerability scanning

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # Continuous Integration Job
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci
      
    - name: Run Linting
      run: npm run lint
      continue-on-error: true # Allow pipeline to continue even if linting fails
      
    - name: Run Unit Tests
      run: npm run test -- --watch=false --browsers=ChromeHeadless
      
    - name: Build Application
      run: npm run build -- --base-href=https://dvcsr.github.io/AngularDevOps/

    - name: Create 404.html for GitHub Pages SPA
      run: cp dist/angular-learning-project/browser/index.html dist/angular-learning-project/browser/404.html
      
    - name: Run Security Audit
      run: npm audit --audit-level=high
      continue-on-error: true # Allow pipeline to continue but report issues
      
    # Upload build artifacts for deployment job
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: dist/

  # Continuous Deployment Job
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: ci # Only run if CI passes
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    # Required permissions for GitHub Pages deployment
    permissions:
      contents: read
      pages: write
      id-token: write
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: dist/
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist/angular-learning-project/
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4